---
title: "Firth's penalized logistic regregssion"
author: "Moses Otieno"
date: "2025-02-26"
categories: [statistics]
bibliography: references.bib
---

## Abstract

The National Mental Health Survey of India (NMHS) was a ground-breaking nationwide study that harnessed a uniform, standardized methodology blending quantitative and qualitative approaches. Covering data from 12 states across diverse regions, its mission was to gauge the prevalence of psychiatric disorders, bridge treatment gaps, explore service utilization, and gauge the socioeconomic repercussions of these conditions. This initiative provided pivotal insights into the intricate landscape of mental health in India. One of the analyses planned for NMHS data was to undertake a logistic regression analysis with an aim to unravel how various sociodemographic factors influence the presence or absence of specific psychiatric disorders. Within this pursuit, two substantial challenges loomed. The first pertained to data separation, a complication that could perturb parameter estimation. The second challenge stemmed from the existence of disorders with lower prevalence rates, which resulted in datasets of limited density, potentially undermining the statistical reliability of our analysis. In response to these data-driven hurdles, NMHS recognized the critical necessity for an alternative to conventional logistic regression, one that could adeptly navigate these complexities, ensuring robust and dependable insights from the collected data. Traditional logistic regression, a widely prevalent method for modeling binary outcomes, has its limitations, especially when faced with limited datasets and rare outcomes. Here, the problem of "complete separation" can lead to convergence failure in traditional logistic regression estimations, a conundrum frequently encountered when handling binary variables. Firth's penalized logistic regression emerges as a potent solution to these challenges, effectively mitigating analytical biases rooted in small sample sizes, rare events, and complete separation. This article endeavors to illuminate the superior efficacy of Firth's method in managing small datasets within scientific research and advocates for its more widespread application. We provide a succinct introduction to Firth's method, emphasizing its distinct advantages over alternative analytical approaches and underscoring its application to data from the NMHS 2015--2016, particularly for disorders with lower prevalence.

This is good paper on firth penalised logistic regression. For more

[@suhas2023]
